name: Python Test Action
description: Runs Python unit tests
inputs:
  ecr_repo:
    required: false
    type: string
  s3_bucket_name:
    required: false
    type: string
  cloudfront_distribution_id:
    required: false
    type: string
  main_branch:
    required: false
    type: string
  prod_repository_uri:
    required: true
    type: string
  repository_uri:
    required: true
    type: string

runs:
  using: "composite"
  steps:


    - name: Checkout source
      uses: actions/checkout@v4
      # run: echo "GITHUB_REF_NAME=`echo $(git describe --tags --abbrev=0)`" >> $GITHUB_ENV

    - name: Configure AWS credentials
      shell: bash
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

