name: Trigger Reusable Workflow

on:
  push:
    branches: [main]

jobs:
  call-reusable:
    uses: atitMula/docker-gs-ping/.github/workflows/golang-prod.yaml@main

    with:
      ecr_repo: "golang"
      s3_bucket_name: 
      cloudfront_distribution_id: 
    secrets: inherit
