name: Trigger Reusable Workflow

on:
  push:
    branches: [main]

jobs:
  call-reusable:
    permissions:
      contents: read
      id-token: write
    uses: atitMula/reusable/.github/workflows/golang-prod.yaml@main

    with:
      ecr_repo: "golang"
      # s3_bucket_name: ${s3_bucket_name}
      # cloudfront_distribution_id: ${cloudfront_distribution_id}
      # main_branch: ${main_branch}
      # PROD_REPOSITORY_URI: ${aws_ecr_repository.prod.repository_url}
      # REPOSITORY_URI: ${aws_ecr_repository.nonprod.repository_url}
      s3_bucket_name:
      cloudfront_distribution_id:
      main_branch: main
      prod_repository_uri: 966085404185.dkr.ecr.us-east-1.amazonaws.com/golang-prod
      repository_uri: 966085404185.dkr.ecr.us-east-1.amazonaws.com/golang
    secrets: inherit
