name: Trigger Reusable Workflow

on:
  push:
    branches: [main]

# on:
#   push:
#     tags:        
#       - '**'
      # - 'v*.*.*'
jobs:
  call-reusable:
    permissions:
      contents: read
      id-token: write
    uses: 0xAtit/reusable/.github/workflows/golang-prod.yaml@main

    with:
      # ecr_repo: ${{ github.event.repository.name }}
      # s3_bucket_name: ${s3_bucket_name}
      # cloudfront_distribution_id: ${cloudfront_distribution_id}
      # main_branch: ${main_branch}
      # PROD_REPOSITORY_URI: ${aws_ecr_repository.prod.repository_url}
      # REPOSITORY_URI: ${aws_ecr_repository.nonprod.repository_url}
      # github_repo: ${github_repo}
      # s3_bucket_name:
      # cloudfront_distribution_id:
      main_branch: main
      prod_repository_uri: 966085404185.dkr.ecr.us-east-1.amazonaws.com/${{ github.event.repository.name }}
      repository_uri: 966085404185.dkr.ecr.us-east-1.amazonaws.com/${{ github.event.repository.name }}
    secrets: inherit
